### ISSUE TITLE
’set‘ object is not subscriptable

### ISSUE THREAD

**Issue by zhulinyv** [sena-nana/MutsukiBot#2]
第20行获取superuser id是不是需要转换成整型，否则报错：
![image](https://user-images.githubusercontent.com/66541860/187396578-23e97117-2b5a-4057-aeca-68f3d1102cc6.png)

这样就没有报错了。
`superuser = int(get_driver().config.superusers[0])`

**Comment by sena-nana** [comment]
这个问题是superusers以set类型储存导致的，改成int并不会解决这个问题。我已经注意到了这个问题，会在之后的版本修复，在那之前可以把superusers[0]改成master，然后在配置文件里加一个master来储存string类型的qq号来解决

**Comment by sena-nana** [comment]
已经更新了，重新安装插件即可

**Comment by zhulinyv** [comment]
> 

了解了，但是int确实有效。

**Comment by sena-nana** [comment]
> > 
> 
> 了解了，但是int确实有效。

我这边试了，并不行。可能是其他的原因导致了报错消失
